services:
  # Сервис ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    ports:
      - "${CLICKHOUSE_PORT:-8123}:8123"
      - "${CLICKHOUSE_NATIVE_PORT:-9000}:9000"
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ${CLICKHOUSE_FOLDER}/data:/var/lib/clickhouse
      - ${CLICKHOUSE_FOLDER}/logs:/var/log/clickhouse-server      
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Сервис Flask приложения
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "${FLASK_PORT:-5001}:5001"
    volumes:
      - .:/app  # Монтируем код для hot-reload при разработке
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - PAGE_LINK=${PAGE_LINK}
      #- PYTHONUNBUFFERED=1
    #depends_on:
    #  clickhouse:
    #    condition: service_healthy
